version: "3"
services:
  ssh:
    image: danielguerra/alpine-sshd
    ports:
     - "5022:22"
  web:
    build: .
    ports:
     - "5000:80"
    volumes:
     - .:/app
  redis:
    image: "redis:alpine"