version: '2'
services:
  ssh:
    image: danielguerra/alpine-sshd
    ports:
     - "5022:22"
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  redis:
    image: "redis:alpine"