logging.level:
  org.jetbrains.exposed: debug
  org.springframework:
    jdbc.core: debug
  Exposed: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exposed?useUnicode=yes&characterEncoding=UTF-8
    username: exposed
    password: exposed